# Scaffolding generated by Casein v5.3.1.0

module Casein
  class ToursController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]

    def index
      @casein_page_title = 'Tours'
      @tours = Tours.order(sort_order(:name)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View tours'
      @tours = Tours.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new tours'
      @tours = Tours.new
    end

    def create
      @tours = Tours.new tours_params

      if @tours.save
        flash[:notice] = 'Tours created'
        redirect_to casein_tours_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new tours'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update tours'

      @tours = Tours.find params[:id]

      if @tours.update_attributes tours_params
        flash[:notice] = 'Tours has been updated'
        redirect_to casein_tours_path
      else
        flash.now[:warning] = 'There were problems when trying to update this tours'
        render action: :show
      end
    end

    def destroy
      @tours = Tours.find params[:id]

      @tours.destroy
      flash[:notice] = 'Tours has been deleted'
      redirect_to casein_tours_path
    end

    private

    def tours_params
      params.require(:tours).permit(:name, :description)
    end
  end
end
